/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression.impl;

import m2.idm.project.mLRegression.Algo;
import m2.idm.project.mLRegression.Calculate;
import m2.idm.project.mLRegression.Dataset;
import m2.idm.project.mLRegression.EvaluationType;
import m2.idm.project.mLRegression.MLRegression;
import m2.idm.project.mLRegression.MLRegressionPackage;
import m2.idm.project.mLRegression.Variables;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ML Regression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.impl.MLRegressionImpl#getDataset <em>Dataset</em>}</li>
 *   <li>{@link m2.idm.project.mLRegression.impl.MLRegressionImpl#getVars <em>Vars</em>}</li>
 *   <li>{@link m2.idm.project.mLRegression.impl.MLRegressionImpl#getEvaluation <em>Evaluation</em>}</li>
 *   <li>{@link m2.idm.project.mLRegression.impl.MLRegressionImpl#getAlgo <em>Algo</em>}</li>
 *   <li>{@link m2.idm.project.mLRegression.impl.MLRegressionImpl#getCalculate <em>Calculate</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MLRegressionImpl extends MinimalEObjectImpl.Container implements MLRegression
{
  /**
   * The cached value of the '{@link #getDataset() <em>Dataset</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDataset()
   * @generated
   * @ordered
   */
  protected Dataset dataset;

  /**
   * The cached value of the '{@link #getVars() <em>Vars</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVars()
   * @generated
   * @ordered
   */
  protected Variables vars;

  /**
   * The cached value of the '{@link #getEvaluation() <em>Evaluation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvaluation()
   * @generated
   * @ordered
   */
  protected EvaluationType evaluation;

  /**
   * The cached value of the '{@link #getAlgo() <em>Algo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlgo()
   * @generated
   * @ordered
   */
  protected Algo algo;

  /**
   * The cached value of the '{@link #getCalculate() <em>Calculate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCalculate()
   * @generated
   * @ordered
   */
  protected Calculate calculate;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MLRegressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MLRegressionPackage.Literals.ML_REGRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dataset getDataset()
  {
    return dataset;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDataset(Dataset newDataset, NotificationChain msgs)
  {
    Dataset oldDataset = dataset;
    dataset = newDataset;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__DATASET, oldDataset, newDataset);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDataset(Dataset newDataset)
  {
    if (newDataset != dataset)
    {
      NotificationChain msgs = null;
      if (dataset != null)
        msgs = ((InternalEObject)dataset).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__DATASET, null, msgs);
      if (newDataset != null)
        msgs = ((InternalEObject)newDataset).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__DATASET, null, msgs);
      msgs = basicSetDataset(newDataset, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__DATASET, newDataset, newDataset));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variables getVars()
  {
    return vars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVars(Variables newVars, NotificationChain msgs)
  {
    Variables oldVars = vars;
    vars = newVars;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__VARS, oldVars, newVars);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVars(Variables newVars)
  {
    if (newVars != vars)
    {
      NotificationChain msgs = null;
      if (vars != null)
        msgs = ((InternalEObject)vars).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__VARS, null, msgs);
      if (newVars != null)
        msgs = ((InternalEObject)newVars).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__VARS, null, msgs);
      msgs = basicSetVars(newVars, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__VARS, newVars, newVars));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EvaluationType getEvaluation()
  {
    return evaluation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEvaluation(EvaluationType newEvaluation, NotificationChain msgs)
  {
    EvaluationType oldEvaluation = evaluation;
    evaluation = newEvaluation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__EVALUATION, oldEvaluation, newEvaluation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEvaluation(EvaluationType newEvaluation)
  {
    if (newEvaluation != evaluation)
    {
      NotificationChain msgs = null;
      if (evaluation != null)
        msgs = ((InternalEObject)evaluation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__EVALUATION, null, msgs);
      if (newEvaluation != null)
        msgs = ((InternalEObject)newEvaluation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__EVALUATION, null, msgs);
      msgs = basicSetEvaluation(newEvaluation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__EVALUATION, newEvaluation, newEvaluation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Algo getAlgo()
  {
    return algo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAlgo(Algo newAlgo, NotificationChain msgs)
  {
    Algo oldAlgo = algo;
    algo = newAlgo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__ALGO, oldAlgo, newAlgo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlgo(Algo newAlgo)
  {
    if (newAlgo != algo)
    {
      NotificationChain msgs = null;
      if (algo != null)
        msgs = ((InternalEObject)algo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__ALGO, null, msgs);
      if (newAlgo != null)
        msgs = ((InternalEObject)newAlgo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__ALGO, null, msgs);
      msgs = basicSetAlgo(newAlgo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__ALGO, newAlgo, newAlgo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Calculate getCalculate()
  {
    return calculate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCalculate(Calculate newCalculate, NotificationChain msgs)
  {
    Calculate oldCalculate = calculate;
    calculate = newCalculate;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__CALCULATE, oldCalculate, newCalculate);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCalculate(Calculate newCalculate)
  {
    if (newCalculate != calculate)
    {
      NotificationChain msgs = null;
      if (calculate != null)
        msgs = ((InternalEObject)calculate).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__CALCULATE, null, msgs);
      if (newCalculate != null)
        msgs = ((InternalEObject)newCalculate).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MLRegressionPackage.ML_REGRESSION__CALCULATE, null, msgs);
      msgs = basicSetCalculate(newCalculate, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MLRegressionPackage.ML_REGRESSION__CALCULATE, newCalculate, newCalculate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MLRegressionPackage.ML_REGRESSION__DATASET:
        return basicSetDataset(null, msgs);
      case MLRegressionPackage.ML_REGRESSION__VARS:
        return basicSetVars(null, msgs);
      case MLRegressionPackage.ML_REGRESSION__EVALUATION:
        return basicSetEvaluation(null, msgs);
      case MLRegressionPackage.ML_REGRESSION__ALGO:
        return basicSetAlgo(null, msgs);
      case MLRegressionPackage.ML_REGRESSION__CALCULATE:
        return basicSetCalculate(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MLRegressionPackage.ML_REGRESSION__DATASET:
        return getDataset();
      case MLRegressionPackage.ML_REGRESSION__VARS:
        return getVars();
      case MLRegressionPackage.ML_REGRESSION__EVALUATION:
        return getEvaluation();
      case MLRegressionPackage.ML_REGRESSION__ALGO:
        return getAlgo();
      case MLRegressionPackage.ML_REGRESSION__CALCULATE:
        return getCalculate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MLRegressionPackage.ML_REGRESSION__DATASET:
        setDataset((Dataset)newValue);
        return;
      case MLRegressionPackage.ML_REGRESSION__VARS:
        setVars((Variables)newValue);
        return;
      case MLRegressionPackage.ML_REGRESSION__EVALUATION:
        setEvaluation((EvaluationType)newValue);
        return;
      case MLRegressionPackage.ML_REGRESSION__ALGO:
        setAlgo((Algo)newValue);
        return;
      case MLRegressionPackage.ML_REGRESSION__CALCULATE:
        setCalculate((Calculate)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MLRegressionPackage.ML_REGRESSION__DATASET:
        setDataset((Dataset)null);
        return;
      case MLRegressionPackage.ML_REGRESSION__VARS:
        setVars((Variables)null);
        return;
      case MLRegressionPackage.ML_REGRESSION__EVALUATION:
        setEvaluation((EvaluationType)null);
        return;
      case MLRegressionPackage.ML_REGRESSION__ALGO:
        setAlgo((Algo)null);
        return;
      case MLRegressionPackage.ML_REGRESSION__CALCULATE:
        setCalculate((Calculate)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MLRegressionPackage.ML_REGRESSION__DATASET:
        return dataset != null;
      case MLRegressionPackage.ML_REGRESSION__VARS:
        return vars != null;
      case MLRegressionPackage.ML_REGRESSION__EVALUATION:
        return evaluation != null;
      case MLRegressionPackage.ML_REGRESSION__ALGO:
        return algo != null;
      case MLRegressionPackage.ML_REGRESSION__CALCULATE:
        return calculate != null;
    }
    return super.eIsSet(featureID);
  }

} //MLRegressionImpl
