/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression.impl;

import java.util.Collection;

import m2.idm.project.mLRegression.MLRegressionPackage;
import m2.idm.project.mLRegression.PredictiveVars;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Predictive Vars</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.impl.PredictiveVarsImpl#getPredVar <em>Pred Var</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PredictiveVarsImpl extends MinimalEObjectImpl.Container implements PredictiveVars
{
  /**
   * The cached value of the '{@link #getPredVar() <em>Pred Var</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPredVar()
   * @generated
   * @ordered
   */
  protected EList<String> predVar;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PredictiveVarsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MLRegressionPackage.Literals.PREDICTIVE_VARS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getPredVar()
  {
    if (predVar == null)
    {
      predVar = new EDataTypeEList<String>(String.class, this, MLRegressionPackage.PREDICTIVE_VARS__PRED_VAR);
    }
    return predVar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MLRegressionPackage.PREDICTIVE_VARS__PRED_VAR:
        return getPredVar();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MLRegressionPackage.PREDICTIVE_VARS__PRED_VAR:
        getPredVar().clear();
        getPredVar().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MLRegressionPackage.PREDICTIVE_VARS__PRED_VAR:
        getPredVar().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MLRegressionPackage.PREDICTIVE_VARS__PRED_VAR:
        return predVar != null && !predVar.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (predVar: ");
    result.append(predVar);
    result.append(')');
    return result.toString();
  }

} //PredictiveVarsImpl
