/*
 * generated by Xtext 2.23.0
 */
package m2.idm.project.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import m2.idm.project.ide.contentassist.antlr.internal.InternalMLRegressionParser;
import m2.idm.project.services.MLRegressionGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MLRegressionParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MLRegressionGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MLRegressionGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getCalculateTypeAccess().getAlternatives(), "rule__CalculateType__Alternatives");
			builder.put(grammarAccess.getEvaluationTypeAccess().getAlternatives(), "rule__EvaluationType__Alternatives");
			builder.put(grammarAccess.getAlgoTypeAccess().getAlternatives(), "rule__AlgoType__Alternatives");
			builder.put(grammarAccess.getTypeValueAccess().getAlternatives(), "rule__TypeValue__Alternatives");
			builder.put(grammarAccess.getNumericValueAccess().getAlternatives(), "rule__NumericValue__Alternatives");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAlternatives_0(), "rule__BooleanValue__ValueAlternatives_0");
			builder.put(grammarAccess.getMLRegressionAccess().getGroup(), "rule__MLRegression__Group__0");
			builder.put(grammarAccess.getCalculateAccess().getGroup(), "rule__Calculate__Group__0");
			builder.put(grammarAccess.getDatasetAccess().getGroup(), "rule__Dataset__Group__0");
			builder.put(grammarAccess.getPartitionAccess().getGroup(), "rule__Partition__Group__0");
			builder.put(grammarAccess.getCrossValidationAccess().getGroup(), "rule__CrossValidation__Group__0");
			builder.put(grammarAccess.getVariablesAccess().getGroup(), "rule__Variables__Group__0");
			builder.put(grammarAccess.getListePredictiveVarAccess().getGroup(), "rule__ListePredictiveVar__Group__0");
			builder.put(grammarAccess.getListePredictiveVarAccess().getGroup_3(), "rule__ListePredictiveVar__Group_3__0");
			builder.put(grammarAccess.getTargetVarAccess().getGroup(), "rule__TargetVar__Group__0");
			builder.put(grammarAccess.getTargetVarAccess().getGroup_3(), "rule__TargetVar__Group_3__0");
			builder.put(grammarAccess.getAlgoAccess().getGroup(), "rule__Algo__Group__0");
			builder.put(grammarAccess.getLineRegressAccess().getGroup(), "rule__LineRegress__Group__0");
			builder.put(grammarAccess.getLineRegressAccess().getGroup_3(), "rule__LineRegress__Group_3__0");
			builder.put(grammarAccess.getDecisionTreeRegressorAccess().getGroup(), "rule__DecisionTreeRegressor__Group__0");
			builder.put(grammarAccess.getSVRAccess().getGroup(), "rule__SVR__Group__0");
			builder.put(grammarAccess.getNumberValueAccess().getGroup(), "rule__NumberValue__Group__0");
			builder.put(grammarAccess.getNumberValueAccess().getGroup_1(), "rule__NumberValue__Group_1__0");
			builder.put(grammarAccess.getPercentValueAccess().getGroup(), "rule__PercentValue__Group__0");
			builder.put(grammarAccess.getMLRegressionAccess().getDatasetAssignment_0(), "rule__MLRegression__DatasetAssignment_0");
			builder.put(grammarAccess.getMLRegressionAccess().getEvaluationAssignment_1(), "rule__MLRegression__EvaluationAssignment_1");
			builder.put(grammarAccess.getMLRegressionAccess().getVarsAssignment_2(), "rule__MLRegression__VarsAssignment_2");
			builder.put(grammarAccess.getMLRegressionAccess().getCalculateAssignment_3(), "rule__MLRegression__CalculateAssignment_3");
			builder.put(grammarAccess.getMLRegressionAccess().getAlgoAssignment_4(), "rule__MLRegression__AlgoAssignment_4");
			builder.put(grammarAccess.getCalculateAccess().getCalculateTypeAssignment_2(), "rule__Calculate__CalculateTypeAssignment_2");
			builder.put(grammarAccess.getCalculateTypeAccess().getTypeAssignment_0(), "rule__CalculateType__TypeAssignment_0");
			builder.put(grammarAccess.getCalculateTypeAccess().getTypeAssignment_1(), "rule__CalculateType__TypeAssignment_1");
			builder.put(grammarAccess.getCalculateTypeAccess().getTypeAssignment_2(), "rule__CalculateType__TypeAssignment_2");
			builder.put(grammarAccess.getDatasetAccess().getDataAssignment_1(), "rule__Dataset__DataAssignment_1");
			builder.put(grammarAccess.getEvaluationTypeAccess().getTypeAssignment_0(), "rule__EvaluationType__TypeAssignment_0");
			builder.put(grammarAccess.getEvaluationTypeAccess().getTypeAssignment_1(), "rule__EvaluationType__TypeAssignment_1");
			builder.put(grammarAccess.getPartitionAccess().getTrainAssignment_2(), "rule__Partition__TrainAssignment_2");
			builder.put(grammarAccess.getPartitionAccess().getTestAssignment_4(), "rule__Partition__TestAssignment_4");
			builder.put(grammarAccess.getCrossValidationAccess().getKAssignment_2(), "rule__CrossValidation__KAssignment_2");
			builder.put(grammarAccess.getVariablesAccess().getPredictivesAssignment_0(), "rule__Variables__PredictivesAssignment_0");
			builder.put(grammarAccess.getVariablesAccess().getTargetsAssignment_1(), "rule__Variables__TargetsAssignment_1");
			builder.put(grammarAccess.getListePredictiveVarAccess().getVarsAssignment_2(), "rule__ListePredictiveVar__VarsAssignment_2");
			builder.put(grammarAccess.getListePredictiveVarAccess().getVarsAssignment_3_1(), "rule__ListePredictiveVar__VarsAssignment_3_1");
			builder.put(grammarAccess.getTargetVarAccess().getVarsAssignment_2(), "rule__TargetVar__VarsAssignment_2");
			builder.put(grammarAccess.getTargetVarAccess().getVarsAssignment_3_1(), "rule__TargetVar__VarsAssignment_3_1");
			builder.put(grammarAccess.getAlgoAccess().getAlgoAssignment_2(), "rule__Algo__AlgoAssignment_2");
			builder.put(grammarAccess.getAlgoTypeAccess().getTypeAssignment_0(), "rule__AlgoType__TypeAssignment_0");
			builder.put(grammarAccess.getAlgoTypeAccess().getTypeAssignment_1(), "rule__AlgoType__TypeAssignment_1");
			builder.put(grammarAccess.getAlgoTypeAccess().getTypeAssignment_2(), "rule__AlgoType__TypeAssignment_2");
			builder.put(grammarAccess.getLineRegressAccess().getColumnsAssignment_2(), "rule__LineRegress__ColumnsAssignment_2");
			builder.put(grammarAccess.getLineRegressAccess().getColumnsAssignment_3_1(), "rule__LineRegress__ColumnsAssignment_3_1");
			builder.put(grammarAccess.getDecisionTreeRegressorAccess().getRandAssignment_2(), "rule__DecisionTreeRegressor__RandAssignment_2");
			builder.put(grammarAccess.getSVRAccess().getParamAssignment_2(), "rule__SVR__ParamAssignment_2");
			builder.put(grammarAccess.getTypeValueAccess().getTypeAssignment_0(), "rule__TypeValue__TypeAssignment_0");
			builder.put(grammarAccess.getTypeValueAccess().getTypeAssignment_1(), "rule__TypeValue__TypeAssignment_1");
			builder.put(grammarAccess.getTypeValueAccess().getTypeAssignment_2(), "rule__TypeValue__TypeAssignment_2");
			builder.put(grammarAccess.getTypeValueAccess().getTypeAssignment_3(), "rule__TypeValue__TypeAssignment_3");
			builder.put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
			builder.put(grammarAccess.getNumericValueAccess().getTypeAssignment_0(), "rule__NumericValue__TypeAssignment_0");
			builder.put(grammarAccess.getNumericValueAccess().getTypeAssignment_1(), "rule__NumericValue__TypeAssignment_1");
			builder.put(grammarAccess.getNumberValueAccess().getValueAssignment_0(), "rule__NumberValue__ValueAssignment_0");
			builder.put(grammarAccess.getNumberValueAccess().getDecimalAssignment_1_1(), "rule__NumberValue__DecimalAssignment_1_1");
			builder.put(grammarAccess.getIntegerValueAccess().getValueAssignment(), "rule__IntegerValue__ValueAssignment");
			builder.put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MLRegressionGrammarAccess grammarAccess;

	@Override
	protected InternalMLRegressionParser createParser() {
		InternalMLRegressionParser result = new InternalMLRegressionParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MLRegressionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MLRegressionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
