/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Calculate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.Calculate#getCalculateType <em>Calculate Type</em>}</li>
 * </ul>
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getCalculate()
 * @model
 * @generated
 */
public interface Calculate extends EObject
{
  /**
   * Returns the value of the '<em><b>Calculate Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calculate Type</em>' attribute.
   * @see #setCalculateType(String)
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getCalculate_CalculateType()
   * @model
   * @generated
   */
  String getCalculateType();

  /**
   * Sets the value of the '{@link m2.idm.project.mLRegression.Calculate#getCalculateType <em>Calculate Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Calculate Type</em>' attribute.
   * @see #getCalculateType()
   * @generated
   */
  void setCalculateType(String value);

} // Calculate
