/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Regress</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.LineRegress#getLeftSidePredict <em>Left Side Predict</em>}</li>
 * </ul>
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getLineRegress()
 * @model
 * @generated
 */
public interface LineRegress extends AlgoType
{
  /**
   * Returns the value of the '<em><b>Left Side Predict</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Side Predict</em>' attribute.
   * @see #setLeftSidePredict(String)
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getLineRegress_LeftSidePredict()
   * @model
   * @generated
   */
  String getLeftSidePredict();

  /**
   * Sets the value of the '{@link m2.idm.project.mLRegression.LineRegress#getLeftSidePredict <em>Left Side Predict</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Side Predict</em>' attribute.
   * @see #getLeftSidePredict()
   * @generated
   */
  void setLeftSidePredict(String value);

} // LineRegress
