/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Regress</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.LineRegress#getColumns <em>Columns</em>}</li>
 * </ul>
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getLineRegress()
 * @model
 * @generated
 */
public interface LineRegress extends AlgoML
{
  /**
   * Returns the value of the '<em><b>Columns</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Columns</em>' attribute list.
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getLineRegress_Columns()
   * @model unique="false"
   * @generated
   */
  EList<String> getColumns();

} // LineRegress
