/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Liste Predictive Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.ListePredictiveVar#getVarPred <em>Var Pred</em>}</li>
 *   <li>{@link m2.idm.project.mLRegression.ListePredictiveVar#getPredVar <em>Pred Var</em>}</li>
 * </ul>
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getListePredictiveVar()
 * @model
 * @generated
 */
public interface ListePredictiveVar extends EObject
{
  /**
   * Returns the value of the '<em><b>Var Pred</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Pred</em>' attribute.
   * @see #setVarPred(String)
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getListePredictiveVar_VarPred()
   * @model
   * @generated
   */
  String getVarPred();

  /**
   * Sets the value of the '{@link m2.idm.project.mLRegression.ListePredictiveVar#getVarPred <em>Var Pred</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Pred</em>' attribute.
   * @see #getVarPred()
   * @generated
   */
  void setVarPred(String value);

  /**
   * Returns the value of the '<em><b>Pred Var</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pred Var</em>' attribute list.
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getListePredictiveVar_PredVar()
   * @model unique="false"
   * @generated
   */
  EList<String> getPredVar();

} // ListePredictiveVar
