/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Partition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.Partition#getTrain <em>Train</em>}</li>
 *   <li>{@link m2.idm.project.mLRegression.Partition#getTest <em>Test</em>}</li>
 * </ul>
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getPartition()
 * @model
 * @generated
 */
public interface Partition extends EvaluationType
{
  /**
   * Returns the value of the '<em><b>Train</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Train</em>' attribute.
   * @see #setTrain(int)
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getPartition_Train()
   * @model
   * @generated
   */
  int getTrain();

  /**
   * Sets the value of the '{@link m2.idm.project.mLRegression.Partition#getTrain <em>Train</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Train</em>' attribute.
   * @see #getTrain()
   * @generated
   */
  void setTrain(int value);

  /**
   * Returns the value of the '<em><b>Test</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Test</em>' attribute.
   * @see #setTest(int)
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getPartition_Test()
   * @model
   * @generated
   */
  int getTest();

  /**
   * Sets the value of the '{@link m2.idm.project.mLRegression.Partition#getTest <em>Test</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Test</em>' attribute.
   * @see #getTest()
   * @generated
   */
  void setTest(int value);

} // Partition
