/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Percent Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getPercentValue()
 * @model
 * @generated
 */
public interface PercentValue extends TypeValue
{
} // PercentValue
