/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predictive Vars</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.PredictiveVars#getPredVar <em>Pred Var</em>}</li>
 * </ul>
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getPredictiveVars()
 * @model
 * @generated
 */
public interface PredictiveVars extends EObject
{
  /**
   * Returns the value of the '<em><b>Pred Var</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pred Var</em>' attribute list.
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getPredictiveVars_PredVar()
   * @model unique="false"
   * @generated
   */
  EList<String> getPredVar();

} // PredictiveVars
