/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target Vars</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link m2.idm.project.mLRegression.TargetVars#getTargetVar <em>Target Var</em>}</li>
 * </ul>
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getTargetVars()
 * @model
 * @generated
 */
public interface TargetVars extends EObject
{
  /**
   * Returns the value of the '<em><b>Target Var</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Var</em>' attribute list.
   * @see m2.idm.project.mLRegression.MLRegressionPackage#getTargetVars_TargetVar()
   * @model unique="false"
   * @generated
   */
  EList<String> getTargetVar();

} // TargetVars
