/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.mLRegression;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see m2.idm.project.mLRegression.MLRegressionPackage#getTypeValue()
 * @model
 * @generated
 */
public interface TypeValue extends EObject
{
} // TypeValue
