/*
 * generated by Xtext 2.23.0
 */
package m2.idm.project;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MLRegressionRuntimeModule extends AbstractMLRegressionRuntimeModule {
}
