/**
 * generated by Xtext 2.23.0
 */
package m2.idm.project.generator;

import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MLRegressionGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    boolean _ressourceAccepted = this.ressourceAccepted(resource);
    if (_ressourceAccepted) {
      fsa.generateFile("test", "good");
    } else {
      fsa.generateFile("test", "error");
    }
  }
  
  public boolean ressourceAccepted(final Resource resource) {
    final TreeIterator<EObject> contents = resource.getAllContents();
    int nbContents = 0;
    while (contents.hasNext()) {
      nbContents++;
    }
    if ((nbContents == 6)) {
      return true;
    }
    return false;
  }
}
