/*
 * generated by Xtext 2.23.0
 */
package m2.idm.project.ui.tests;

import com.google.inject.Injector;
import m2_idm_project.ui.internal.M2_idm_projectActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MLRegressionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return M2_idm_projectActivator.getInstance().getInjector("m2.idm.project.MLRegression");
	}

}
